README.md
Pull request related to https://github.com/emin93/react-native-template-typescript/issues/35
=> Add link for migrate instructions from existing project

_gitignore
Updated to reflect react native template.
=> Updated pods fix.

.travis.yml, README.md
Added new init command doc and updated travis configuration
=> added new init command doc

template/_gitignore, template/android/app/src/main/java/com/helloworld/MainActivity.java, template/android/app/src/main/java/com/helloworld/MainApplication.java, template/android/gradle/wrapper/gradle-wrapper.properties, template/ios/HelloWorldTests/HelloWorldTests.m, template/package.json
Updated template to match the latest default RN template
=> updated template to match the latest RN template

App.tsx
according to [react-ntive website](https://facebook.github.io/react-native/docs/hermes/#confirming-hermes-is-in-use) there should be a notice when you switch to hermes engine.
init a new app and replace old `App.tsx` with new `App.tsx`
=> add hermes engine notice

App.tsx
Re: https://github.com/facebook/react-native/issues/25882 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37303
Will allow the default app to compile out of the box.
=> Update App.tsx to correspond to def typed updates

README.md
The default Readme displayed on github does not show the recommended way to use this template with RN >= 0.60.
fixes #57
=> Fix suggested usage for RN >= 0.60

template/App.tsx
=> fixed wrong credit url

README.md
There has been quite a few confusion about the old CLI, even with the note in the `README.md`. So I added an extension with the link to the new CLI readme for further assistance.
I hope this will solve a lot of trouble.
=> added further notes on the legacy CLI

README.md
Added RN 0.60 usage to README.
=> Add RN 0.60 usage to readme

README.md
Reverts react-native-community/react-native-template-typescript#89
=> Revert "Fix Usage on README"

template/package.json
=> Update for RN 0.61.3

template/package.json
=> Update for 0.61.4

README.md
I made "Note on the legacy CLI" stand out by reordering sections, because it is important information for users.
I tried sometimes `react-native init MyApp --template react-native-template-typescript` with legacy react-native-cli. This PR is for users like me.
=> Make note on the legacy CLI stand out

template/App.tsx
Closes #114 
Change App.tsx a bit so that yarn lint will pass after initialization.
npx react-native init example --template react-native-template-typescript
yarn lint
=> Apply prettier to template

template/package.json
Updated version of `@types/react-native` which allows users to use the `useWindowDimensions` hooks added in RN 0.61.
Also, updated version of the community eslint-config to latest to reflect the template on react-native core
https://github.com/facebook/react-native/blob/master/template/package.json
create init from this template, updated eslint-config and @types/react-native to verify that there are no erroes in lint or tsc.
=> chore: update @types/react-native and community eslint-config

README.md, template/package.json
Upgrades README and eslint-config to latest version.
=> Upgrade README and eslint-config

template/android/gradlew
Fixes incorrect formatting in template's Android gradlew file
Broken case formatting could cause the gradle wrapper not to work on certain systems.
- [N/A] I have tested this on a device and a simulator
- [N/A] I added the documentation in `README.md`
- [] I mentioned this change in `CHANGELOG.md`
- [N/A] I updated the typed files (TS and Flow)
- [N/A] I added a sample use of the API in the example project (`example/App.js`)
=> fix formatting for gradlew case statement

template/package.json
=> Upgrade @types/react-native to the corresponding version of react-native

template/package.json
Sort devDependencies in package.json file
When creating a new project, devDependencies are not sorted correctly.
=> style: sort devDependencies in package.json

template/package.json
Updated react native version to 0.63.4.
This PR covers issue #172 .
=> Sync react native verison 0.63.4 and update packages

template/App.tsx
=> fix: App.tsx types and indentation

template/App.tsx
Just a minor text correction regarding the file ending App.tsx
=> correcting template text on the welcome screen

template/package.json
Update typescript template to 0.66.2
=> feat: update to react native 0.66.2

template/package.json
Update typescript template to 0.66.3
[React Native(v0.66.3)](https://github.com/facebook/react-native/releases/tag/v0.66.3)
=> feat: update to react native 0.66.3

template/package.json
Update typescript template to 0.66.4
=> feat: update to react native 0.66.4

template/Gemfile.lock, template/package.json
Summary
Update typescript template to 0.67.2
=> feat: update to react native 0.67.2

template/Gemfile
=> correcting typos

template/Gemfile.lock, template/package.json
Updated according to the [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.67.2&to=0.67.3).
=> feat: update to react-native@0.67.3

.github/workflows/npm-publish-prerelease.yml
To be able to distinguish in the overview:
=> Rename prerelease workflow

.github/workflows/lint.yml
Added a lint check so we can verify if the template compiles.
=> feat: lint check

template/ios/Podfile, template/package.json
https://react-native-community.github.io/upgrade-helper/?from=0.69.1&to=0.69.2
=> feat: update to react-native@0.69.2

template/package.json
https://react-native-community.github.io/upgrade-helper/?from=0.69.2&to=0.69.3
=> feat: update to react-native@0.69.3

template/ios/HelloWorld.xcodeproj/project.pbxproj, template/ios/Helloworld.xcworkspace/contents.xcworkspacedata, template/package.json
[React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.70.0&to=0.70.1)
=> feat: update to react-native@0.70.1

template/ios/HelloWorld.xcodeproj/project.pbxproj, template/package.json
https://react-native-community.github.io/upgrade-helper/?from=0.70.3&to=0.70.4
=> feat: update to react-native@0.70.4

template/package.json
https://react-native-community.github.io/upgrade-helper/?from=0.70.5&to=0.70.6
=> feat: update to react-native 0.70.6
