react-native-community/react-native-template-typescript

setup.js

hello there 👋,
really cool template @emin93, easy to follow + simple and efficient idea!
while using it during this week, I found myself tweaking `setup.js` before running `node setup.js` to use `yarn`,
in this PR, I'm adding support for `yarn` and also inheriting the parent process in `execSync`, so you can see the `stdio` from `yarn add` or `npm i` in the process (not only warnings/errors)
like:
thanks! 🤗

[feat] add support for Yarn + inheriting exec process

---

App.tsx
__tests__/App.tsx
devDependencies.json
tsconfig.json

New features in tsconfig allow us to stay closer to the default react-native template.
Specifically,
"allowSyntheticDefaultImports": true, 
"esModuleInterop": true
allow us to import the same as react-native default template.
```
import React from 'react';
```

Enable esModuleInterop

---

tsconfig.json

On a newly created project, after running setup.js, `npm run tsc` fails with the error: `babel.config.js:1:1 - error TS1208: Cannot compile namespaces when the '--isolatedModules' flag is provided`. This patch adds babel.config.js to the exclude setting in tsconfig.json.

Add babel.config.js to TypeScript excludes

---

README.md
__tests__/App.tsx
devDependencies.json
jest.json
setup.js
tsconfig.json

In this PR I re-added `ts-jest` to enable out of the box jest testing with TypeScript.

Added ts-jest

---

tsconfig.json

In the latest RC of React Native (0.59.0-rc.3) a `metro.config.js` file is created with the following content:
```js
/**
* Metro configuration for React Native
* https://github.com/facebook/react-native
*
* @format
*/
module.exports = {
transformer: {
getTransformOptions: async () => ({
transform: {
experimentalImportSupport: false,
inlineRequires: false,
},
}),
},
};
```
When you run `tsc`, it fails with this error:
```
metro.config.js:8:1 - error TS1208: Cannot compile namespaces when the '--isolatedModules' flag is provided.
8 module.exports = {
~~~~~~
Found 1 error.
```
This PR fixes that error by excluding the `metro.config.js` file just like we did for `babel.config.js`.

Add metro.config.js to tsconfig excluded files

---

_gitignore

I had to manually add the `/ios/Pods` folder to my `.gitignore`, after having created a project using `react-native init MyProject --template typescript`. This PR aims to fix that.

Add Pods folder to .gitignore

---

template/ios/Podfile

This PR fixes error when react-native-cli installs pod dependencies. react-native@0.60.0 seems that it still depends on React-fishhook so I added it to the Podfile. https://github.com/facebook/react-native/blob/v0.60.0/template/ios/Podfile#L9.
This command successfully initializes a new project.
```
npx react-native init MyApp --template=https://github.com/LukeSugiura/react-native-template-typescript#master-cli-v2
```
```
npx react-native init MyApp --template=react-native-template-typescript@next
```

[cli-v2] Fix pod dependency error

---

.travis.yml
README.md

In this PR, I removed support for the legacy version of the template. New tags on master will now trigger a build and release a new version on npm.

Deprecate legacy

---

README.md

Currently, `npx react-native init MyApp --template react-native-template-typescript` throws an error because react-native-cli is trying to fetch `react-native-template-react-native-template-typescript`, so `react-native-template` prefix is redundant here
Just run the current command explained in README.md to face an issue

fix(readme): init script

---

.travis.yml

This PR should fix the Travis build, inspired by the legacy configuration which worked just fine (https://github.com/react-native-community/react-native-template-typescript/commit/0ab55f4385ae4208242d1f9c066b3dadc32ae6a1#diff-354f30a63fb0907d4ad57269548329e3).
Unfortunately there's no way to test it (except creating a new repository and do it there, but I feel like that might be an overkill right now).
So let's hope this fixes it 😄

removed branch condition

---

README.md

Reverts react-native-community/react-native-template-typescript#62
Somehow the user had an old CLI version - https://github.com/react-native-community/react-native-template-typescript/pull/62#issuecomment-530544789

Revert "fix(readme): init script"

---

README.md

Small update to the README. Adding a note about removing the globally installed **react-native-cli** before running `npx react-native init MyApp --template react-native-template-typescript`
https://github.com/react-native-community/react-native-template-typescript/issues/64#issuecomment-531098495
N/A
N/A

README - Adding note on uninstalling react-native-cli

---

template/App.tsx

Fixes #71
Actually `HermesIternal` was added to `types/react-native` a long time ago but we just have to use it in the right way.

Fix issue with global.HermesIternal

---

tsconfig.json

default tsconfig.json added Closes #70

---

template/tsconfig.json

TypeScript ships with a `react-native` [JSX mode](https://www.typescriptlang.org/docs/handbook/jsx.html#basic-usage).
This PR also closes https://github.com/react-native-community/react-native-template-typescript/pull/86 for moving `tsconfig.json` to the right `template` folder. This prevents a merge conflict later on.

Update jsx from react to react-native

---

README.md

Apparently currently the option `--template` already adds the `react-native-template` to the path, and if we use what's on README we will have this path that doesn't exist:
https://registry.yarnpkg.com/react-native-template-react-native-template-typescript
Changing to just `--template typescript` fixes it.
Follow the README Usage instructions

Fix Usage on README

---

template/package.json

Resolves https://github.com/react-native-community/react-native-template-typescript/issues/99
Updated Typescript version to 3.7.3 and confirmed that optional chaining works in fresh project.
Create a new component which takes in an optional prop:
``` typescript
import React from 'react';
import {Text} from 'react-native';
interface Props {
optionalFunction?: () => void;
}
const Test = ({optionalFunction}: Props) => {
optionalFunction?.();
return <Text>Testing optional chaining</Text>;
};
export default Test;
```
Include this new component in `App.tsx` and test passing a valid or undefined function. If the function is defined then it should execute before rendering. Something simple like `() => console.log('Optional changing works!')` is an easy check.
| ------- | …

Upgrade typescript to 3.7.3.

---

template/package.json

React native is initialised by default with eslint rules, but we need some parsers to make this work with typescript.
Run `yarn lint` on console

added eslint dependencies for typescript

---

template/package.json

In the `@react-native-community/eslint-config` package a quite outdated version of prettier is used which does not support the nullish chaining yet. While adding prettier to the devDependencies, this bug is fixed.

Fixed prettier nullish chaining bug

---

template/App.tsx

Our custom global variable would be nicer declared as a `const`.
`var` doesn't seem to present any advantages here.
Functionality-wise the block scope remains the same as the global scope.
Semantic-wise it's clear it is global as @emin93 already moved it below imports.
Also ib4 wave of ESLint `no-var` adopters (e.g. [gabts/eslint-config-react-native-typescript](https://github.com/gabts/eslint-config-react-native-typescript))
Further: https://eslint.org/docs/rules/no-var#when-not-to-use-it
- Add `'no-var': 'off'` to _.eslintrc_ rules
- Or try [gabts/eslint-config-react-native-typescript](https://github.com/gabts/eslint-config-react-native-typescript)
- `yarn lint`

Update App.tsx custom global variable declaration

---

template/tsconfig.json

Removed `baseUrl` from `.tsconfig` as this causes several IDEs to do the auto imports wrong.
Either include it in the babel config as well or remove it from the `.tsconfig`, because now there's a mismatch between the tsconfig and the babel config.

Removed baseUrl from .tsconfig

---

.gitignore
template/android/app/build.gradle
template/ios/HelloWorld.xcodeproj/project.pbxproj
template/package.json

Update versions of react-native and @types/react-native to 0.63.2 version

feat: update react-native to 0.63.2 and @types/react-native to 0.63.2

---

template/android/gradle.properties
template/package.json

Thought it might make sense to re-sync the template again with the latest RN template and there are in fact a few things we didn't take over yet.
Template source as usual from the official RN repo (tag v0.63.3): https://github.com/facebook/react-native/tree/v0.63.3/template

sync latest rn 

---

template/_eslintrc.js
template/package.json

Remove redudant TS Parser and Plugin from template eslintrc since react-native-community/eslint-config has this configuration https://github.com/facebook/react-native/blob/master/packages/eslint-config-react-native-community/index.js#L54-L55
Close #149 
Everything should work as before

Remove redundant TS parser and plugin

---

template/tsconfig.json

Currently running the Typescript compiler on the template throws over 177 errors (See gist https://gist.github.com/sshquack/1e0d1425a10fbfa2b6eab91c8eeda235#file-rn-tsc-errors for full list of errors).
All the errors are because `tsc` is finding duplicate types exposed in the `node_modules`. The fix is to skip the library check while doing type resolution per the compiler flag `skipLibCheck` https://www.typescriptlang.org/tsconfig#skipLibCheck
```
$ yarn run tsc
node_modules/@types/react-test-renderer/node_modules/@types/react/index.d.ts(2982,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
node_modules/@types/react-test-renderer/node_modules/@types/react/index.d.ts(2995,13): error TS2717: Subsequent property declarations must have the same type.  Property 'a' must be …
```

Fix compile errors with skip lib check

---

template/tsconfig.json

Now that React Native 0.63 requires iOS 10.x, and bundles a modern version of JSC on Android, we can update the JavaScript library version to es2017. That brings in declarations for:
- `Array.prototype.includes`
- `Object.entries` and `Object.values`
- `String.padStart` and `String.padEnd`
Also, the version of Node that React Native requires, 10.x, also supports these APIs.
Ran `yarn run tsc` in the template application and no errors were found.
N/A
N/A

Fix lib to use iOS 10.x and Android JSC

---

template/package.json
template/tsconfig.json

This is an alternative to #181 to fix the compile errors from type checking dependencies. The compiler errors are caused by multiple copies of `@types/react` being brought in by yarn. This happens because both `@types/react-native` and `@types/react-test-renderer` declare a dependency on `@types/react`, but they have different version dependencies, which causes duplication:
```
"@types/react-native@^0.63.2":
version "0.63.49"
resolved "https://registry.yarnpkg.com/@types/react-native/-/react-native-0.63.49.tgz#b9a4781a0543763f0079c3ef2ba2148a4509b32e"
dependencies:
"@types/react" "*"
"@types/react-test-renderer@^16.9.2":
version "16.9.5"
resolved "https://registry.yarnpkg.com/@types/react-test-renderer/-/react-test-renderer-16.9.5.tgz#edab67da470f7c3e997f58d55dcfe2643cc30a68" …
```

Prevent installing multiple versions of `@types/react`

---

template/package.json

typings for RN0.64 has been released and we should make the change here as well .

deps: bump @types/react-native to 0.64.0

---

template/package.json

Note: While the upgrade helper shows a modified `project.pbxproj`:
https://react-native-community.github.io/upgrade-helper/?from=0.64.0&to=0.64.1
this file hasn't been updated in the RN repo:
https://github.com/facebook/react-native/blob/v0.64.1/template/ios/HelloWorld.xcodeproj/project.pbxproj

upgrade to rn 0.64.1 and update type defs

---

template/tsconfig.json

I can't find any reason why this isn't enabled already and it was added in TypeScript 2.9 so should work for everyone.

Allow TypeScript to resolve JSON modules

---

README.md

This is a suggestion to improve the communication about the React Native CLI. As it works only with the new CLI, it seems to be a requirement instead of a note.
The goal here is to avoid issues like this one https://github.com/facebook/react-native/issues/31054.

Update documentation to have CLI instructions before the usage

---

README.md
template/_gitignore
template/android/app/build.gradle
template/android/app/src/main/res/values/styles.xml
template/android/build.gradle
template/android/gradle.properties
template/ios/HelloWorld.xcodeproj/project.pbxproj
template/ios/Podfile
template/package.json

Update typescript template to 0.66.0

feat: update to react native 0.66.0

---

template/_eslintrc.js

In pure javascript eslint config from `@react-native-community`, the no-shadow rule is on,
which is good, but for typescript it generates false-positives and needs a specific configuration change
to use a typescript-specific rule
Reference: 
- Rule: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-shadow.md
- Problems: https://github.com/typescript-eslint/typescript-eslint/issues/2552#issuecomment-691694839

fix(lint): typescript requires special no-shadow

---

template/_eslintrc.js
template/package.json

There are several issues related to the current ESLint/TypeScript setup with the latest version of this template.
Steps to reproduce:
1. Create new project: `npx react-native init rntsapp --template react-native-template-typescript`
2. Run `yarn lint`
3. Observe errors
```
error  Definition for rule '@typescript-eslint/no-shadow' was not found  @typescript-eslint/no-shadow
```
and
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
```
Also, `.eslintrc.js` contained a few quote warnings/errors that were also fixed.
```
/path/rntsapp/.eslintrc.js
1:1   error    Definition for rule '@typescript-eslint/no-shadow' was not found                                    @typescript-eslint/no-shadow
5:5   error …
```

Fix ESLint setup

---

template/_eslintrc.js

A couple of minor updates to the ESLint config:
- Move rules into an `overrides` section, as these should only be applied to TypeScript files (`.ts`/`.tsx`)
- Disable `no-undef`
The reason for disabling `no-undef` can be found in the [official typescript-eslint docs](https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/TROUBLESHOOTING.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors):
> We strongly recommend that you do not use the no-undef lint rule on TypeScript projects. The checks it provides are already provided by TypeScript without the need for configuration - TypeScript just does this significantly better.

Update ESLint config

---

template/tsconfig.json

when running `tsc` on a project inited with this template (v6.9.0), the following errors are thrown:
```
node_modules/@types/node/globals.d.ts:47:11 - error TS2300: Duplicate identifier 'AbortController'.
47 interface AbortController {
~~~~~~~~~~~~~~~
node_modules/@types/react-native/globals.d.ts:435:15
435 declare class AbortController {
~~~~~~~~~~~~~~~
'AbortController' was also declared here.
node_modules/@types/node/globals.d.ts:60:11 - error TS2300: Duplicate identifier 'AbortSignal'.
60 interface AbortSignal {
~~~~~~~~~~~
node_modules/@types/react-native/globals.d.ts:400:15
400 declare class AbortSignal implements EventTarget {
~~~~~~~~~~~
'AbortSignal' was also declared here.
node_modules/@types/node/globals.d.ts:67:13 - error TS2300: Duplicate identifier 'AbortController'.
67 …
```

set skipLibCheck to true in tsconfig

---

.gitignore
template/tsconfig.json

This aligns `tsconfig.json` with the default as generated by `tsc --init` (using TypeScript 4.6.4).
TypeScript has updated the format (mainly ordering and documentation) of `tsconfig.json` starting with TypeScript 4.4
While there are many line changes, there are **zero configuration changes**: The values for `target`, `module`, `lib`, etc. **remain the same** - Any potential future updates should be done in a separate PR, not mixed with a (primarily) visual formatting change.
The _only new option_ added (which TS now includes by default), is `"forceConsistentCasingInFileNames": true`, which I think is good to have.
Adding a `// prettier-ignore` comment at line 1 of the file ensures Prettier does not accidentally reformat the whole file, resulting in misalignment of documentation comments …

Align tsconfig.json with TypeScript 4.4+

---

template/tsconfig.json

```
npx react-native init MyApp --template react-native-template-typescript
cd MyApp
```

Fix for "Type 'Timeout' is not assignable to type 'number'"

---

README.md
template/Gemfile
template/_gitignore
template/android/app/build.gradle
template/android/app/src/main/java/com/helloworld/MainActivity.java
template/android/app/src/main/java/com/helloworld/newarchitecture/MainApplicationReactNativeHost.java
template/android/app/src/main/jni/Android.mk
template/android/build.gradle
template/android/settings.gradle
template/ios/HelloWorld.xcodeproj/project.pbxproj
template/ios/HelloWorld/AppDelegate.mm
template/ios/Podfile
template/ios/_xcode.env
template/package.json
template/tsconfig.json

feat: update to 0.69.0

---

template/package.json
template/tsconfig.json

Context
- https://github.com/tsconfig/bases/pull/116
To keep our recommended React Native TSConfig base as the source
---
`yarn set version classic`
_Have a think if [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) should be recommended for React Native, we do in [few others](https://github.com/tsconfig/bases/search?q=skipLibCheck)_
<s>Remove duplicate rule overrides</s>
<s>Keep duplicate rule overrides for visibility</s>

Extend recommended React Native TSConfig base

---

template/package.json

As discussed in #298, if we decide to add `@types/react` to the template this PR should work

Add @types/react to devDependencies

---

template/ios/HelloWorld.xcodeproj/project.pbxproj

Fixes regression caused by:#308
See: https://github.com/react-native-community/react-native-template-typescript/pull/308/files#diff-5e5f05dcdf7a14aea292c3172649e6a220923662fdb41d409997c37da721d27eR565
```
pod install
.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:284:in `raise_parser_error': [!] Invalid character "\\xE2" in unquoted string (Nanaimo::Reader::ParseError)
565>                            "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = ”;
^
```

fix: syntax error in iOS xcodeproject

---

README.md

Added a little info that this repo is now no longer supported.

feat: add deprecation message

---

template/Gemfile
template/package.json

The template should update to the latest minor changes the version 0.70.10
Different for updating is safe https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.70.10
Version 0.70.10 fixes the build failed issue in iOS 12.0 that mentioned in https://github.com/facebook/react-native/issues/34106#issuecomment-1601242383

feat: update to react-native@0.70.10
